name: flutter_carousel_widget_example
description: Demonstrates how to use the flutter_carousel_widget plugin.
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_carousel_widget:
    path: ../

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
