name: flutter_carousel_widget
description: A customizable carousel slider widget in Flutter which supports infinte scrolling, auto scrolling, custom child widget, custom animations and pre-built indicators.
version: 0.1.3
homepage: https://github.com/nixrajput/flutter_carousel_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: